model_list:
  - model_name: claude-opus-4-5
    litellm_params:
      model: vertex_ai/claude-opus-4-5
      vertex_ai_project: "YOUR_PROJECT_ID"
      vertex_ai_location: "global"
      drop_params: true

litellm_settings:
  master_key: "YOUR_API_KEY"
  drop_params: true
  modify_params: true
